name: Build OrmLite

on:
  push:
    paths:
      - 'ServiceStack.OrmLite/**'
      - '.github/workflows/build-ormlite.yml'

jobs:
  build-ormlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          
          
      - name: Build
        working-directory: ServiceStack.OrmLite/build
        run: dotnet build ./build.proj
                
      - name: Env setup
        run: |
          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV
        
      - name: Tests Setup
        working-directory: ServiceStack.OrmLite/tests
        run: dotnet test --framework net10.0 ./ServiceStack.OrmLite.Tests.Setup/ServiceStack.OrmLite.Tests.Setup.csproj        

      - name: Test Sqlite
        working-directory: ServiceStack.OrmLite/tests
        env:
          ORMLITE_DIALECT: Sqlite
        run: dotnet test --framework net10.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: OrmLite Tests
          only-summary: 'true'
          path: ./ServiceStack.OrmLite/tests/ServiceStack.OrmLite.SqliteTests/TestResults/test-results.trx
          reporter: dotnet-trx
          